consumes:
- application/json
info:
  title: TcbHomework
  version: 0.1.0
produces:
- application/json
schemes:
- http
swagger: "2.0"
paths: 
  /api/pools/add:
    post:
      description: insert/append values to pools
      tags:
        - pool
      operationId: insertPool
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/poolObject"
      responses:
        200:
         description: OK
         schema:
            $ref: "#/definitions/poolObjectAddResponse"
        default:
          description: generic error response
          schema:
             $ref: "#/definitions/errorResponse"
  /api/pools/query:
    post:
      description: get calculatedQuantile for a given pool id and percentile 
      tags:
        - pool
      operationId: querryPool
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/poolQueryRequest"
      responses:
        200:
         description: OK
         schema:
            $ref: "#/definitions/poolQueryResponse"
        default:
          description: generic error response
          schema:
             $ref: "#/definitions/errorResponse"
definitions:
  poolObject:
    type: object
    required:
      - poolId
      - poolValues
    properties: 
      poolId:
        type: number
        format: int64
      poolValues:
        type: array
        maxItems: 1000000
        items:
          type: number
          format: int32
    additionalProperties: false
  poolObjectAddResponse:
    description: return add status, staus fileld value will be either "appended" or "inserted"
    type: object
    required:
      - status
    properties: 
      status:
        type: string
  errorResponse:
    type: string
  poolQueryRequest:
    type: object
    required:
      - poolId
      - percentile
    properties:
      poolId:
        type: number
        format: int64
      percentile:
        type: number
        format: double
  poolQueryResponse:
    type: object
    required:
      - calculatedQuantile
      - totalCount
    properties: 
      calculatedQuantile:
        type: number 
        format: int32 
      totalCount:
        type: number
        format: int64