consumes:
- application/json
info:
  title: Percentile
  version: 0.1.0
produces:
- application/json
schemes:
- http
swagger: "2.0"
paths: 
  /api/pools/add:
    post:
      description: insert/append values to pools
      tags:
        - pool
      operationId: insertPool
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/poolObject"
      responses:
        200:
         description: OK
         schema:
            $ref: "#/definitions/poolObjectAddResponse"
        400:
          description: "Bad Client Request"
          schema:
            $ref: "#/definitions/errorResponse"
        default:
          description: generic error response
          schema:
             $ref: "#/definitions/errorResponse"
  /api/pools/query:
    post:
      description: insert/append values to pools
      tags:
        - pool
      operationId: querryPool
      parameters:
        - name: body
          in: body
          schema:
            $ref: "#/definitions/poolQueryRequest"
      responses:
        200:
         description: OK
         schema:
            $ref: "#/definitions/poolObjectAddResponse"
        400:
          description: "Bad Client Request"
          schema:
            $ref: "#/definitions/errorResponse"
        default:
          description: generic error response
          schema:
             $ref: "#/definitions/errorResponse"
definitions:
  poolObject:
    type: object
    required:
      - poolId
      - poolValues
    properties: 
      poolId:
        type: number
        format: int64
      poolValues:
        type: array
        maxItems: 5
        items:
          type: number
          format: int32
    additionalProperties: false
  poolObjectAddResponse:
    type: object
    required:
      - status
    properties: 
      status:
        type: string
  poolObjectQueryResponse:
    type: object
    required:
      - calculatedQuantile
      - totalCount
    properties: 
      calculatedQuantile:
        type: number
        format: double
      totalCount:
        type: number
        format: int64
  errorResponse:
    type: string
  poolQueryRequest:
    type: object
    required:
      - poolId
      - percentile
    properties:
      poolId:
        type: number
        format: int64
      percentile:
        type: number
        format: double
  poolQueryResponse:
    type: object
    required:
      - calculatedQuantile
      - totalCount
    properties: 
      calculatedQuantile:
        type: number 
        format: double 
      totalCount:
        type: number
        format: int64