// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PoolObjectQueryResponse pool object query response
//
// swagger:model poolObjectQueryResponse
type PoolObjectQueryResponse struct {

	// calculated quantile
	// Required: true
	CalculatedQuantile *float64 `json:"calculatedQuantile"`

	// total count
	// Required: true
	TotalCount *int64 `json:"totalCount"`
}

// Validate validates this pool object query response
func (m *PoolObjectQueryResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCalculatedQuantile(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PoolObjectQueryResponse) validateCalculatedQuantile(formats strfmt.Registry) error {

	if err := validate.Required("calculatedQuantile", "body", m.CalculatedQuantile); err != nil {
		return err
	}

	return nil
}

func (m *PoolObjectQueryResponse) validateTotalCount(formats strfmt.Registry) error {

	if err := validate.Required("totalCount", "body", m.TotalCount); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this pool object query response based on context it is used
func (m *PoolObjectQueryResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PoolObjectQueryResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PoolObjectQueryResponse) UnmarshalBinary(b []byte) error {
	var res PoolObjectQueryResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
